language: php
php:
  - '5.6.31'
  - '7.0'
  - hhvm # on Trusty only
  - nightly
install: php index.php
env:
  - DB=mysql
  - DB=pgsql
before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS food_db;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database food_db;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS food_db;" -uroot; fi
script: phpunit --configuration phpunit_$DB.xml --coverage-text